version: "3.4"

services:
  pariah-nexus-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      pariah-nexus-db:
        condition: service_healthy
        restart: true

  pariah-nexus-db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    # restart: always
    container_name: pariah-nexus-db
    ports:
      - 4444:22
      - 3306:3306
    environment:
      - MYSQL_DATABASE=pariahnexus
      - MYSQL_ROOT_PASSWORD=arasakaOperator123
      - MYSQL_USER=arasakaOperator
      - MYSQL_PASSWORD=arasakaOperator123
    volumes:
      - ./Database/mysql:/var/lib/mysql
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10

networks:
  default:
    driver: bridge