name: Build and Deploy to ECS Service for Pariah-Nexus

on:
  schedule:
    # This cron expression runs the workflow every day at 00:00 UTC
    - cron: '0 4 * * *'

env:
  SERVICE_NAME: pariah-nexus-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.S3_PARIAH_NEXUS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }} 

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build API Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pariah-nexus-api:latest -f ./Dockerfile .

    - name: Build DB Docker image
      run: docker build \
            --build-arg TARGET_S3_BUCKET_NAME=${{ secrets.TARGET_S3_BUCKET_NAME }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/pariah-nexus-db:latest -f ./Database/Dockerfile .

    - name: Push API Docker image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pariah-nexus-api:latest

    - name: Push DB Docker image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pariah-nexus-db:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.TERERAFORM_PARIAH_NEXUS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }} 

    - name: Force new deployment on ECS for API
      run: |
        aws ecs update-service \
          --cluster ${{ secrets.ECS_CLUSTER_ARN }} \
          --service ${{ env.SERVICE_NAME }} \
          --force-new-deployment